apiVersion: v2
name: modulo
description: Chart para publicação do módulo
type: application
version: 0.0.1
dependencies:
  - name: cloud-comp-job
    version: 0.0.12
    repository: https://albatis.github.io/helm-charts/
  - name: cloud-comp
    version: 0.0.37
    repository: https://albatis.github.io/helm-charts/
    alias: playlists-recommender-system
