apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexandrevieira-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alexandrevieira
  template:
    metadata:
      labels:
        app: alexandrevieira
    spec:
      containers:
      - name: alexandrevieira
        image: nginx:latest
        ports:
        - containerPort: 80
