apiVersion: v1
kind: Service
metadata:
  name: alexandrevieira-service
spec:
  selector:
    app: alexandrevieira
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080 # The port the Service exposes internally within the cluster
      targetPort: 80 # The port on the Pod where the application is listening
      nodePort: 30000 # Optional: A specific port on the Node (must be in the range 30000-32767)
