cloud-comp-job:
  name: job-ds1-2023
  login: alexandrevieira
  image: albatis/generator-rules-processor:latest
  resources:
    cpu: 0
    memory: 2G
  environments:
    URL: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds2.csv"
    MIN_SUPPORT: "0.06"
  commandInitContainer: "rm -f /mnt/*; wget --no-check-certificate $URL -P /mnt;"
  volumes:
    - name: project2-pv
      storageClassName: default-storage-class-alexandrevieira
      size: 1Gi
      path: /mnt
      hostPath: /home/alexandrevieira/project2-pv
      accessMode: ReadWriteMany
      ignore: true