# Para trocar os arquivos troque o name, URL e INPUT_FILE_PATH
cloud-comp-job:
  name: job-rules-ds1-s4
  login: alexandrevieira
  image: albatis/generator-rules-processor:latest
  resources:
    cpu: 0
    memory: 2G
  environments:
    URL: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds1.csv"
    MIN_SUPPORT: "0.04"
    INPUT_FILE_PATH: /mnt/2023_spotify_ds1.csv
  commandInitContainer: "rm -f /mnt/*; wget --no-check-certificate $URL -P /mnt;"
  volumes:
    - name: project2-pv
      storageClassName: default-storage-class-alexandrevieira
      size: 1Gi
      path: /mnt
      hostPath: /home/alexandrevieira/project2-pv
      accessMode: ReadWriteMany
      ignore: true
  
playlists-recommender-system:
  name: playlists-recommender-system
  login: alexandrevieira
  image: albatis/playlists-recommender-system:latest
  replicas: 1
  containerPort: 8000
  servicePort: 8080
  nodePort: 30000
  resources:
    cpu: 0
    memory: 2G
  startupProbe:
    httpGet:
      path: /healthz
      port: 8000
    failureThreshold: 30
    periodSeconds: 1
    timeoutSeconds: 5
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /healthz
      port: 8000
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 2
  volumes:
    - name: project2-web
      storageClassName: default-storage-class-alexandrevieira
      size: 1Gi
      path: /mnt
      #hostPath: /home/alexandrevieira/project2-pv
      #accessMode: ReadWriteMany
      ignore: true