cloud-comp:
  name: primeiro
  containerPort: 80
  servicePort: 8080
  nodePort: 30000
  replicas: 1
  image: "albatis/playlists-recommender-system:latest"
  login: alexandrevieira
  resources:
    cpu: 0
    memory: 64Mi
  volume:
    size: 1Gi
    path: /mnt
